### PR TITLE
use Buffer.alloc if available

### PR DESCRIPTION
**Pull request by mafintosh**

### CODE REVIEW

**Comment by LinusU** [comment]
> **Ponyfills should never use the native API, even if available,** as it might have slightly different behavior between environments, which can cause bugs.

Anyhow, I'm flexible with this. Are there any upside to using `Buffer.alloc` though?

**Comment by mafintosh** [comment]
Its gonna be a lot faster since it can use calloc internally instead of malloc

**Comment by mafintosh** [comment]
Sindre's ponyfills does this as well, https://github.com/sindresorhus/buffer-equals/blob/master/index.js

**Comment by LinusU** [comment]
Cool, thanks!

**Pull request merged**
